name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  run_test:
    name: Run Test
    runs-on: ubuntu-latest
    container: golang:1.15

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go env -w GO111MODULE=on && go env -w GOSUMDB=off && go mod tidy

      - name: Go Test
        run: go test ./... 

      - name: build
        run: go build -o proxy-pool exmples/exmple/main.go