# This is a basic workflow to help you get started with Actions
on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

name: Release
jobs:
  run_build:
    name: Run Release
    runs-on: ubuntu-latest
    container: golang:1.14

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go env -w GO111MODULE=on && go env -w GOSUMDB=off && go mod tidy

      - name: build
        run: go build -o proxy-pool exmples/exmple/main.go

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset Mktxt
        id: upload-release-asset-mktxt
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: 
          asset_name: 
          asset_content_type: application/octet-stream
